from data_service.utils import exception


class UsernameNotFound(exception.Error):
    pass
